# Generated by Django 5.0 on 2024-01-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categproductos',
            options={'verbose_name': 'CategoriaProd', 'verbose_name_plural': 'categoriasProd'},
        ),
    ]
