# Generated by Django 5.0 on 2024-01-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
